In [ ]:
import numpy as np
import math

In [ ]:
matrix = [[1,2,3], [4,5,6], [6,7,8]]
[[i + 1 for i in row] for row in matrix]

In [ ]:
#Creating 1 dimension array
array1 = np.array([10,100,1000.])
print(type(array1))
array1

In [ ]:
#Zagnieżdżone
array2 = np.array([[1., 2., 3.], [4.,5.,6.]])
array2

In [ ]:
#Array type checking
array1.dtype

In [ ]:
#Data printing in float
float(array1[2])

In [ ]:
#Operations with arrays (wektorisation)
array2 * array2

In [ ]:
#Broadcasting - expanding smaller array to create a operation
array1 * array2

In [ ]:
#@ iloczyn skalarny 
array2 @ array2.T

In [ ]:
#SQRT from array 2 (short examples)
np.array([[math.sqrt(i) for i in row]for row in array2])
np.sqrt(array2)

In [ ]:
#sum of each column axis=0 (index), axis=1 column
print(array2)
array2.sum(axis=0)

In [ ]:
#Sum of whole matrix
array2.sum()

### Table elements (indexing)

In [ ]:
array3 = np.array([10,100,1000])
array4 = np.array([[1,2,3],
                  [4,5,6]])

In [18]:
#examples of cutting
array3[2]

1000

In [19]:
array4[0,0]


1

In [20]:
array4[0,:]

array([1, 2, 3])

In [24]:
array4[:,1:]

array([[2, 3],
       [5, 6]])

In [22]:
array4[:,1]

array([2, 5])